"""empty message

Revision ID: 6fe43d226814
Revises: 79c7bb597087
Create Date: 2016-01-10 21:25:46.450656

"""

# revision identifiers, used by Alembic.
revision = '6fe43d226814'
down_revision = '79c7bb597087'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsuleers', sa.Column('security_status', sa.Integer(), nullable=True))
    op.drop_column('capsuleers', u'sec_status')
    op.add_column('capsuleers_secstatus_history', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('capsuleers_secstatus_history', u'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsuleers_secstatus_history', sa.Column(u'date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('capsuleers_secstatus_history', 'datetime')
    op.add_column('capsuleers', sa.Column(u'sec_status', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('capsuleers', 'security_status')
    ### end Alembic commands ###
