"""empty message

Revision ID: 79c7bb597087
Revises: None
Create Date: 2016-01-09 15:25:00.882180

"""

# revision identifiers, used by Alembic.
revision = '79c7bb597087'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capsuleers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('sec_status', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capsuleers_corporation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capsuleer_id', sa.Integer(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capsuleer_id'], ['capsuleers.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capsuleers_secstatus_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sec_status', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['capsuleers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capsuleers_secstatus_history')
    op.drop_table('capsuleers_corporation_history')
    op.drop_table('capsuleers')
    op.drop_table('corporations')
    ### end Alembic commands ###
